### ISSUE TITLE
formatting crashes on my Gruntfile.js

### ISSUE THREAD

**Issue by amiiit** [ionutvmi/sublime-jsfmt#17]
When formatting, following exception is being thrown. The file is not getting reformatted.

```
JSFMT
Error: 
/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/jsfmt.js:31
        throw err;
              ^
Error: Line 427: Unexpected string
    at throwError (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1195:13)
    at expect (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1222:13)
    at parseArrayInitialiser (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1320:21)
    at parsePrimaryExpression (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1552:20)
    at /Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1703:20)
    at /Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseUnaryExpression (/Users/amit/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/node_modules/rocambole/node_modules/esprima/esprima.js:1784:16)
```

If there are any more details I could provide please ask.

Thank you

**Comment by rkhayat** [comment]
I am having the same error `The formatting failed please check the console for more details`, Can you point me in the right direction please?

**Comment by ionutvmi** [comment]
@rkhayat I'm not sure that jsfmt offers full support for ES6/7. You can check in their [issues list](https://github.com/rdio/jsfmt/issues) for more info.

**Comment by rkhayat** [comment]
Hi @ionutvmi I have posted in their repo. https://github.com/rdio/jsfmt/issues/169

**Comment by ionutvmi** [comment]
@rkhayat I took a closer look at the error message and it says

```
Cannot find plugin '[object Object]'. Make sure you used the correct name on the config file or run `npm install --save-dev [object Object]` to add it as a project dependency.
```

Can you check if you double check that you installed the plugin correctly ?
You should do an npm install in the folder where jsfmt is installed.

**Comment by rkhayat** [comment]
Aren't you able to install it globally instead of per project? @ionutvmi

**Comment by ionutvmi** [comment]
no, the plugin should not be installed globally.
You only have to install it once in your jsfmt folder.
You can access that by going to Preferences -> Browser Packages -> jsfmt.

The follow the instructions from the esformatter-jsx wiki and it should work.

**Comment by rkhayat** [comment]
I believe it's working now, thank you. Is there a reason my Decorator was replaced with ```____decorator__at_sign___Radium```
