### ISSUE TITLE
project .jsfmtrc doesn't work

### ISSUE THREAD

**Issue by kaktus42** [ionutvmi/sublime-jsfmt#44]
A `.jsfmtrc` file in my project root does not get loaded.

A user sublime-settings works though. How can I make this work?

```
JSFMT ==>
Error: /home/kaktus42/.config/sublime-text-3/Packages/jsfmt/jsfmt.js:31
        throw err;
        ^

SyntaxError: Unexpected token (2:14)
    at Parser.pp.raise (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:2905:8)
    at Parser.pp.semicolon (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:2892:38)
    at Parser.pp.parseExpressionStatement (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:2264:8)
    at Parser.parseExpressionStatement (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:3600:20)
    at Parser.pp.parseStatement (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:1955:17)
    at Parser.parseStatement (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:3578:22)
    at Parser.pp.parseBlockBody (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:2294:21)
    at Parser.pp.parseBlock (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:2275:8)
    at Parser.pp.parseStatement (/home/kaktus42/.config/sublime-text-3/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/babylon/index.js:1914:19)
```

**Comment by ionutvmi** [comment]
jsfmt loads the settings using the rc module.
The locations for the jsfmtrc locations are listed here: https://github.com/dominictarr/rc#standards

In order to format a code you need to have valid JS code in your file. You probably had a syntax error in your file so this is why you got that error in the console.
