### ISSUE TITLE
Error: Cannot find module 'extend'

### ISSUE THREAD

**Issue by Soyrros0x0** [ionutvmi/sublime-jsfmt#54]
```
JSFMT ==>
Error: internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/chiangfai/Library/Application Support/Sublime Text 3/Packages/jsfmt/jsfmt.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)a
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)



reloading settings Packages/User/jsfmt.sublime-settings
error: The formatting failed please check the console for more details.
```

**Comment by FgoPan** [comment]
me too ,I had resolved it.
use `npm i extend --save` in the `\Sublime Text 3\Packages\jsfmt` folder

**Comment by Soyrros0x0** [comment]
thanks,I try
